#Tweaked from Ansible Playbook Demonstration
# 01/11/2019 MG
- name: Play 1 of 2
  hosts: ios 
  gather_facts: no
  connection: network_cli

  vars_prompt:
    - name: 'common_to_both_plays'
      prompt: 'Enter username'
      default: 'cisco'
      private: false

    - name: 'only_in_play_1'
      prompt: 'Enter password'
      default: 'cisco'
      private: true
      unsafe: true

  vars:
      only_play_1 : 'show ip interface brief '  #settable
      backup_path: 'data'    #we don't expect/want someone using this playbook to change this
      both_play_1_and_play_2 : 23.4 #settable
  
  tasks:

    - import_role:
       name: clay584.parse_genie

    - name: configurable backup path
      ios_config:
           backup: yes
           backup_options:
             dir_path: "{{ backup_path }}"  

    - name: execute our ios cmd 
      ios_command:
        commands:
          - "{{ ios_cmd }}" 
      register: my_output  

    - name: extract our data 
      set_fact:
        ip_int_brief: |-
          {{ my_output.stdout[0] | parse_genie(command= ios_cmd, os="ios") }}

    #- pause:
    #    minutes: 5

    - name: display data 
      debug:
        msg: "{{ ip_int_brief }}" 

    - name: make data available to rest of flow
      set_stats:
           data:
             show_ip_int : "{{ ip_int_brief }}"
             int_stat: 42 
             float_stat: 4.2
             true_stat: true
             teapot_string_stat: '42'
             list_stat:
                     - 'hello'
                     - 'world'
                     - 'me'
                     - 'tired'
           aggregate: no


- name: Play 2 of 2
  hosts: ios
  gather_facts: no
  connection: network_cli

  vars_prompt:
    - name: 'common_to_both_plays' # common to both plays, and will prompt the user for one value
      prompt: 'Enter username'
      default: 'cisco' # This may be a lab password 
      private: false

    - name: 'play2_only' # unique to play 2 - user will be asked for ansible_user, ansible_user_2
      prompt: 'Enter username 2!'
      default: 'cisco' # This may be a lab password 
      private: false

    - name: 'ansible_password_2'
      prompt: 'Enter password 2!'
      default: 'cisco' # This may be a lab password 
      private: true
      unsafe: true 

  vars:
      backup_path: 'data'    #TODO - we don't care if there's a duplicate in a non-settable var? 
      both_play_1_and_play_2: 23.4 #settable
      play_2_only: 123.4 #settable

  tasks:

    - import_role:
        name: clay584.parse_genie

    - name: configurable backup path
      ios_config:
        backup: yes
        backup_options:
          dir_path: "{{ backup_path }}"

    - name: execute our ios cmd
      ios_command:
        commands:
          - "{{ ios_cmd }}"
      register: my_output

    - name: extract our data
      set_fact:
        ip_int_brief: |-
          {{ my_output.stdout[0] | parse_genie(command= ios_cmd, os="ios") }}

    #- pause:
    #    minutes: 5

    - name: display data
      debug:
        msg: "{{ ip_int_brief }}"

    - name: make data available to rest of flow
      set_stats:
        data:
          show_ip_int : "{{ ip_int_brief }}"
          int_stat: 42
          float_stat: 4.2
          true_stat: true
          teapot_string_stat: '42'
          list_stat:
            - 'hello'
            - 'world'
            - 'me'
            - 'tired'
        aggregate: no

# TODO set stats would be an aggregate of keys for play1 overlayed by later keys for play2?