- name: Create and Incident in snow  
  hosts: ios  
  gather_facts: false 
  connection: local

  vars_prompt:

    - name: 'sn_username'
      prompt: 'Enter ServiceNow username'
      default: 'admin'
      private: false
      unsafe: true

    - name: 'sn_password'
      prompt: 'Enter ServiceNow password'
      default: 'rybkin-zYrje0-wapziv'
      private: true
      unsafe: true

  vars:
     sn_instance: dev75689  #settable
     my_severity: 3 #settable
     my_priority: 2 #settable
     my_short_description: "Issue with {{ inventory_hostname }}. Please investigate" #settable
     my_description: "An issue with {{ inventory_hostname }} has been detected. Please investigate ASAP" #settable
     incident_data:
        short_description: "{{ my_short_description }}"
        description:  "{{ my_description }}"
        severity: "{{ my_severity }}" 
        priority: "{{ my_priority }}" 
  

  tasks:

  - name: Find open standard changes with my template
    snow_record_find:
      table: cmdb_ci_ip_router 
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      query:
           name: "{{ inventory_hostname }}" 
      return_fields:
        - sys_id  
    delegate_to: localhost
    register: ci 

  - debug: 
      var: ci.record[0].sys_id

 
  - name: add CI record to Incident 
    set_fact:
       incident_data_ci : "{{ incident_data | combine( { 'cmdb_ci': ci.record[0].sys_id }  ) }}"
    when: ci | length > 0


  - name: Create an Incident 
    snow_record:
        state: present
        table: incident 
        username: "{{ sn_username }}"
        password: "{{ sn_password }}"
        instance: "{{ sn_instance }}"
        data: "{{ incident_data_ci }}"
    register: new_incident
    delegate_to: localhost

