---
- name: Ensure git is installed "dsfijeiufhrehgiouehrwiughiorhgioghwiohrig ho gh"
  yum:
    name: git
    state: present
  register: result

- name: "Artifact integration test results to the web"
  local_action: 'shell curl https://file.io'
  register: result

- name: "Git Result"
  set_stats:
    data:
      git_results:  "{{ result.stdout }}"

- name: Ensure jq is installed
  yum:
    name: jq
    state: present

- name: Ensure tree is installed
  yum:
    name: tree
    state: present

- name: Ensure socat is installed
  yum:
    name: socat
    state: present

- name: Ensure nc is installed
  yum:
    name: nc
    state: present

- name: Ensure ag is installed
  yum:
    name: the_silver_searcher
    state: present

- name: Ensure ngrep is installed
  yum:
    name: ngrep
    state: present

- name: Ensure tmux is installed
  yum:
    name: tmux
    state: present

- name: Ensure ncdu is installed
  yum:
    name: ncdu
    state: present

- name: Ensure unzip is installed
  yum:
    name: unzip
    state: present

- name: Ensure lsof is installed
  yum:
    name: lsof
    state: present

- name: Ensure make is installed
  yum:
    name: make
    state: present

- name: Ensure bind-utils is installed
  yum:
    name: bind-utils
    state: present

- name: Ensure dhclient is installed
  yum:
    name: dhclient
    state: present

- name: Ensure strace is installed
  yum:
    name: strace
    state: present

- name: Ensure traceroute is installed
  yum:
    name: traceroute
    state: present

- name: Ensure collectd is removed
  yum:
    name: collectd
    state: absent

- name: Ensure wireshark is installed
  yum:
    name: wireshark
    state: present

- name: upgrade all security packages
  yum:
    name: '*'
    security: yes
    state: latest
