domain-include: virl.info
ignore-invalid-commands: true
crawl: true
auth-break: false
connection-types:  # these two are the only valid responses edited
  - ssh
  - telnet
site-name: test
customer-name: FAKE COMPANY PTY LTD
ucdin: "91218238123"
devices: []
scan:
  timeout: 3
  count: 3
  interval: 0.5
  batch-size: 10
multi-process: false
inventory-merge: 'null'