#test
- name: Configure IOS Device
  hosts: ios
  gather_facts: no
  connection: network_cli

  vars_prompt:
    - name: 'ansible_user'
      prompt: 'Enter username'
      default: 'cisco'
      private: false

    - name: 'ansible_password'
      prompt: 'Enter password'
      default: 'cisco'
      private: true
      unsafe: true

  vars:
      config_section: 'interface GigabitEthernet0/0' #settable
      config_lines: 'description sample description' #settable

  tasks:

    - name: run command 
      ios_config:
          parents:
            - "{{ config_section }}" 
          lines:
            - "{{ config_lines }}" 
          save_when: modified

