---
# paste the following lines into the inventory without the #
# ----------------------- Start-------------------------------
# router1
# router2
# router3
# router4
# router5
# ----------------------- End  ------------------------------
#

- name: failed path
  hosts: all
  gather_facts: no
  connection: local
  any_errors_fatal: yes

  vars:
    fail_on: 'router1' #settable
    fail_enabled: True 

  tasks:

  - name: show the status of the fail_enabled flag
    debug:
      msg: "{{fail_enabled}}"
    run_once: true


  - name: simulating a failure on selected hosts
    fail:
      msg: "deliberately failing on {{ fail_on }}"
    when: fail_enabled and (fail_on in inventory_hostname)

#

...