#Ansible template to obtain the next available list of ip addresses from a provided network .
#network - the network to object the ip address out of 
#number - the number of ip addresses to return

- name: Find Next Network 
  hosts: localhost   
  gather_facts: false 
  connection: local

  vars_prompt:

    - name: 'infoblox_username'
      prompt: 'Enter Infoblox username'
      default: 'admin'
      private: false
      unsafe: true

    - name: 'infoblox_password'
      prompt: 'Enter Infoblox password'
      default: 'infoblox'    
      private: true
      unsafe: true

  vars:
     infoblox_host: 10.47.69.137 #settable
     infoblox:
           host: "{{ infoblox_host }}"
           username: "{{ infoblox_username }}" 
           password: "{{ infoblox_password }}"
     network: '172.0.0.0/8' #settable
     cidr: 24 #settable
     number: 3  #settable
    
     
  
  tasks:

   - name: return next available IP address for specified network
     set_stats:
         data:
            nextnetwork: "{{ lookup('nios_next_network', network, num=number|int, cidr=cidr|int, provider= infoblox ) }}"
     delegate_to: localhost
 
